Repository anoma/juvix-stdlib, pull requests merged in 2023-04, with the labels that each got.

#49 Run `juvix format`
  Stdlib/Data/Bool.juvix
  Stdlib/Data/Int.juvix
  Stdlib/Data/List.juvix
  Stdlib/Data/List/Ord.juvix
  Stdlib/Data/Maybe.juvix
  Stdlib/Data/Nat.juvix
  Stdlib/Data/Nat/Gcd.juvix
  Stdlib/Data/Nat/Ord.juvix
  Stdlib/Data/Ord.juvix
  Stdlib/Data/Product.juvix
  Stdlib/Data/String.juvix
  Stdlib/Data/String/Ord.juvix
  Stdlib/Debug.juvix
  Stdlib/Debug/Fail.juvix
  Stdlib/Debug/Trace.juvix
  Stdlib/Function.juvix
  Stdlib/System/IO.juvix
  index.juvix
Labels: format

#50 Add Judoc comments for most of the functions
  Stdlib/Data/Bool.juvix
  Stdlib/Data/Int.juvix
  Stdlib/Data/Int/Ord.juvix
  Stdlib/Data/List.juvix
  Stdlib/Data/Maybe.juvix
  Stdlib/Data/Nat.juvix
  Stdlib/Data/Nat/Gcd.juvix
  Stdlib/Data/Nat/Ord.juvix
  Stdlib/Data/Product.juvix
  Stdlib/Data/String.juvix
  Stdlib/Data/String/Ord.juvix
  Stdlib/Debug/Fail.juvix
  Stdlib/Debug/Trace.juvix
  Stdlib/Function.juvix
  Stdlib/Prelude.juvix
Labels: documentation

#51 Add Quickcheck testing
  .github/workflows/ci.yml
  Makefile
  test/.gitignore
  test/Makefile
  test/Test.juvix
  test/juvix.yaml
Labels: enhancement
