Repository anoma/juvix-stdlib, pull requests merged in 2023-05, with the labels that each got.

#55 Add some useful functions
  Stdlib/Data/Int.juvix
  Stdlib/Data/List.juvix
  Stdlib/Data/Nat.juvix
  Stdlib/Data/String.juvix
  Stdlib/Data/String/Base.juvix
  Stdlib/Debug/Fail.juvix
  test/Makefile
Labels: enhancement

#54 Add 'traits', Stdlib.Trait.{Ord, Eq, Show}
  Stdlib/Data/Bool.juvix
  Stdlib/Data/Bool/Base.juvix
  Stdlib/Data/Int.juvix
  Stdlib/Data/Int/Base.juvix
  Stdlib/Data/Int/Ord.juvix
  Stdlib/Data/List.juvix
  Stdlib/Data/List/Base.juvix
  Stdlib/Data/List/Ord.juvix
  Stdlib/Data/Maybe.juvix
  Stdlib/Data/Maybe/Base.juvix
  Stdlib/Data/Nat.juvix
  Stdlib/Data/Nat/Base.juvix
  Stdlib/Data/Nat/Ord.juvix
  Stdlib/Data/Product.juvix
  Stdlib/Data/Product/Base.juvix
  Stdlib/Data/String.juvix
  Stdlib/Data/String/Base.juvix
  Stdlib/Data/String/Ord.juvix
  Stdlib/Function.juvix
  Stdlib/Prelude.juvix
  Stdlib/Trait/Eq.juvix
  Stdlib/Trait/Ord.juvix
  Stdlib/Trait/Show.juvix
  index.juvix
  test/Makefile
  test/Test.juvix
Labels: enhancement

#57 fix unlines and add concatStr
  Stdlib/Data/String/Base.juvix
  test/Makefile
Labels: enhancement

#58 Expose functions associated to Traits
  Stdlib/Trait.juvix
  Stdlib/Trait/Eq.juvix
  Stdlib/Trait/Ord.juvix
  Stdlib/Trait/Show.juvix
Labels: enhancement

#56 Add the `Unit` type
  Stdlib/Data/Unit.juvix
  Stdlib/Prelude.juvix
Labels: enhancement

#62 Fix and test for splitAt function
  Stdlib/Data/List/Base.juvix
  test/Test.juvix
Labels: bug

#66 Refactor IO
  Stdlib/System/IO.juvix
  Stdlib/System/IO/Base.juvix
  Stdlib/System/IO/Bool.juvix
  Stdlib/System/IO/Int.juvix
  Stdlib/System/IO/Nat.juvix
  Stdlib/System/IO/String.juvix
Labels: refactor
